#!/usr/bin/env php
<?php

use Xantios\Maple\RunCommand;

// if Dev run
if(file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
}

use Symfony\Component\Console\Application;

$run = new RunCommand();

$application = new Application();
$application->add($run);
$application->setDefaultCommand($run->getName(),true);
$application->run();
