#!/usr/bin/env php
<?php

// if Package run
if(file_exists(realpath(__DIR__.'/../../autoload.php'))) {
    require_once realpath(__DIR__.'/../../autoload.php');
}

// if Dev run
if(file_exists(__DIR__.'/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
}

use Xantios\Maple\RunCommand;
use Symfony\Component\Console\Application;

$run = new RunCommand();

$application = new Application();
$application->add($run);
$application->setDefaultCommand($run->getName(),true);
$application->run();
